-- Adds naming provenance to the buildings table. Idempotent errors on re-run.
-- Generated by scripts/enrich-names.mjs.
ALTER TABLE buildings ADD COLUMN block TEXT;
ALTER TABLE buildings ADD COLUMN name_source TEXT;   -- 'osm' | 'google' | 'block' | NULL
