-- Noise sources per building + the road segments polled live for traffic.
-- Generated by scripts/enrich-sources.mjs from OpenStreetMap. Re-run that to refresh.

CREATE TABLE IF NOT EXISTS segments (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  name           TEXT NOT NULL UNIQUE,
  ref            TEXT,
  road_class     TEXT NOT NULL,
  lat            REAL NOT NULL,
  lon            REAL NOT NULL,
  poll           INTEGER NOT NULL DEFAULT 1,   -- cron polls WHERE poll = 1
  building_count INTEGER NOT NULL DEFAULT 0,   -- buildings within 250 m
  last_polled    TEXT                          -- ISO 8601, updated by the collector
);

CREATE TABLE IF NOT EXISTS building_sources (
  osm_id      INTEGER NOT NULL,   -- buildings.osm_id
  kind        TEXT NOT NULL,      -- 'road' | 'rail'
  class       TEXT NOT NULL,      -- motorway|trunk|primary|secondary | rail|light_rail|subway|monorail
  name        TEXT,
  ref         TEXT,
  distance_m  REAL NOT NULL,      -- nearest approach, metres
  segment_id  INTEGER,           -- segments.id when this source is polled live, else NULL
  PRIMARY KEY (osm_id, kind, class)
);
CREATE INDEX IF NOT EXISTS idx_building_sources_osm ON building_sources(osm_id);

-- readings gains a segment_id (old rows stay NULL; joined by name as before)
-- Applied separately in sources_seed.sql via ALTER TABLE (ignored if present).
